pldm-fw: use write_all for extract_component
Use write_all() instead of write(), as write() may only be partial.

error: written amount is not handled
   --> pldm-fw/src/main.rs:120:5
    |
120 |     f.write(&buf)?;
    |     ^^^^^^^^^^^^^^

Signed-off-by: Jeremy Kerr <jk@codeconstruct.com.au>